export const SAVE_USERADDRESS = "save_useraddress"
export const SAVE_CATEGORYS = "save_categorys"
export const SAVE_SHOPLIST = "save_shoplist"
export const SAVE_USERDETAIL = "save_userdetail"
export const SAVE_USERTOKEN = "save_usertoken"
export const LOG_OUT = "log_out"
